### ISSUE TITLE
use post->ID as it's more reliable way

### ISSUE THREAD

**Issue by lordspace** [orbisius/orbisius-support-tickets-addon-attachments#2]
https://github.com/orbisius/orbisius-support-tickets-addon-attachments/blob/953a78b292d908862527e116bd0c89d31d2197f4/include/ost-aa-class-public.php#L211

**Comment by lordspace** [comment]
it seems the ID was used but why would you need $attachment->guid at all?
When the site is migrated this could change

**Comment by carlfromfelton** [comment]
attachment->guid is not needed anymore since we are going to serve the file via PHP
